DOC-4228: New pages for cdm
datastax/migration-docs pull request #168
Opened 2024-04-15 18:28 UTC by beajohnson

2024-05-22 21:13 UTC, msmygit approved these changes
lgtm 👍🏼

2024-05-22 21:14 UTC, msmygit commented on modules/ROOT/pages/cdm-steps.adoc
> +Use {cstar-data-migrator} to identify large fields from a table that may break your cluster guardrails.
```suggestion
Use {cstar-data-migrator} to identify large fields from a table that may break your https://docs.datastax.com/en/astra-db-serverless/cql/cassandra-guardrails.html[cluster guardrails].
```

2024-06-06 21:22 UTC, jeromatron approved these changes
I think this will be great to have.  We might just want to double check with Faizal and Pravin and the CDM team are happy with these details.

2024-06-07 14:54 UTC, KimberlyFields requested changes

2024-06-13 11:59 UTC, beajohnson commented on modules/ROOT/nav.adoc
> +* xref:cassandra-data-migrator.adoc[]
Canceling the ticket DOC-4235 as I've added the nav to this ticket.

2024-06-13 15:48 UTC, KimberlyFields requested changes

2024-06-13 15:48 UTC, KimberlyFields commented on modules/ROOT/pages/cassandra-data-migrator.adoc
> += Introduction to {cstar-data-migrator}
Remove "Introduction to". This page ends up including everything about CDM, so it's not just an intro.

2024-06-13 15:48 UTC, KimberlyFields commented on modules/ROOT/pages/cassandra-data-migrator.adoc
> +The fat jar, or`cassandra-data-migrator-x.y.z.jar`, file should be present now in the `target` folder.
```suggestion
The fat jar file, `cassandra-data-migrator-x.y.z.jar`, should be present now in the `target` folder.
```

2024-06-13 20:22 UTC, beajohnson commented on modules/ROOT/nav.adoc
> +** xref:cassandra-data-migrator.adoc[Overview]
I've tried making partials with this nav full of xrefs and keep getting errors. Unfortunately, the links have to remain xrefs.

2024-06-14 18:10 UTC, KimberlyFields approved these changes
I made 2 comments, but I'm approving this PR.

2024-06-14 18:10 UTC, KimberlyFields commented on modules/ROOT/pages/cdm-steps.adoc
> += {cstar-data-migrator}
```suggestion
= Migrate data using the {cstar-data-migrator}
```

2024-06-14 18:10 UTC, KimberlyFields commented on modules/ROOT/nav.adoc
Do you still need this nav file in this PR if you are going to create a separate PR for the overall nav updates for migration?

2024-06-14 18:21 UTC, beajohnson commented on modules/ROOT/nav.adoc
I like this nav best and it has the most changes.

2024-06-14 19:57 UTC, merged